## Online shopping Data Analysis

In [2]:
import numpy as np
from numpy import genfromtxt

Data = genfromtxt('DS1_C4_S1_Shopping_Data_Challenge.csv', delimiter = ',', skip_header = 1)
print(Data)

[[  1.  19.  15.  39.]
 [  2.  21.  15.  81.]
 [  3.  20.  16.   6.]
 [  4.  23.  16.  77.]
 [  5.  31.  17.  40.]
 [  6.  22.  17.  76.]
 [  7.  35.  18.   6.]
 [  8.  23.  18.  94.]
 [  9.  64.  19.   3.]
 [ 10.  30.  19.  72.]
 [ 11.  67.  19.  14.]
 [ 12.  35.  19.  99.]
 [ 13.  58.  20.  15.]
 [ 14.  24.  20.  77.]
 [ 15.  37.  20.  13.]
 [ 16.  22.  20.  79.]
 [ 17.  35.  21.  35.]
 [ 18.  20.  21.  66.]
 [ 19.  52.  23.  29.]
 [ 20.  35.  23.  98.]
 [ 21.  35.  24.  35.]
 [ 22.  25.  24.  73.]
 [ 23.  46.  25.   5.]
 [ 24.  31.  25.  73.]
 [ 25.  54.  28.  14.]
 [ 26.  29.  28.  82.]
 [ 27.  45.  28.  32.]
 [ 28.  35.  28.  61.]
 [ 29.  40.  29.  31.]
 [ 30.  23.  29.  87.]
 [ 31.  60.  30.   4.]
 [ 32.  21.  30.  73.]
 [ 33.  53.  33.   4.]
 [ 34.  18.  33.  92.]
 [ 35.  49.  33.  14.]
 [ 36.  21.  33.  81.]
 [ 37.  42.  34.  17.]
 [ 38.  30.  34.  73.]
 [ 39.  36.  37.  26.]
 [ 40.  20.  37.  75.]
 [ 41.  65.  38.  35.]
 [ 42.  24.  38.  92.]
 [ 43.  48.  39.  36.]
 [ 44.  31.

In [31]:
# Task 1

#Assigning Variables to each column

cust_id = Data[:,0]
age = Data[:,1]
annual_income = Data[:,2]
spend_score = Data[:,3]


index = np.where(spend_score>80)
score_morethan_80 = spend_score[index]
print("---------------------------------------------------------------")
print("*Details of the customers whose spending score is more than 80*")
print("---------------------------------------------------------------")
print("\nCustomer ID:\n",cust_id[index])
print("\nAge:\n",age[index])
print("\nAnnual Income:\n",annual_income[index])
print("\nSpending Score:\n",score_morethan_80)

# Display total count of these customers

print("=========================================================================")
print("\nTotal count of customers whose spending score is more than 80 is:", cust_id[index].size)

---------------------------------------------------------------
*Details of the customers whose spending score is more than 80*
---------------------------------------------------------------

Customer ID:
 [  2.   8.  12.  20.  26.  30.  34.  36.  42. 124. 128. 136. 142. 144.
 146. 150. 152. 156. 162. 164. 168. 174. 176. 180. 182. 184. 186. 190.
 194. 200.]

Age:
 [21. 23. 35. 35. 29. 23. 18. 21. 24. 39. 40. 29. 32. 32. 28. 34. 39. 27.
 29. 31. 33. 36. 30. 35. 32. 29. 30. 36. 38. 30.]

Annual Income:
 [ 15.  18.  19.  23.  28.  29.  33.  33.  38.  69.  71.  73.  75.  76.
  77.  78.  78.  78.  79.  81.  86.  87.  88.  93.  97.  98.  99. 103.
 113. 137.]

Spending Score:
 [81. 94. 99. 98. 82. 87. 92. 81. 92. 91. 95. 88. 93. 87. 97. 90. 88. 89.
 83. 93. 95. 92. 86. 90. 86. 88. 97. 85. 91. 83.]

Total count of customers whose spending score is more than 80 is: 30


In [32]:
# Task 2

indx = np.where((age>20) & (age<24))
age_group = age[indx]

print("--------------------------------------------------------")
print("*Details of the customers whose age is between 20 to 24*")
print("--------------------------------------------------------")
print("\nCustomer ID:\n",cust_id[indx])
print("\nAge:\n",age_group)
print("\nAnnual Income:\n",annual_income[indx])
print("\nSpending Score:\n", spend_score[indx])


--------------------------------------------------------
*Details of the customers whose age is between 20 to 24*
--------------------------------------------------------

Customer ID:
 [  2.   4.   6.   8.  16.  30.  32.  36.  79.  85.  88. 101. 106. 125.]

Age:
 [21. 23. 22. 23. 22. 23. 21. 21. 23. 21. 22. 23. 21. 23.]

Annual Income:
 [15. 16. 17. 18. 20. 29. 30. 33. 54. 54. 57. 62. 62. 70.]

Spending Score:
 [81. 77. 76. 94. 79. 87. 73. 81. 52. 57. 55. 41. 42. 29.]


In [45]:
# Task 3

lowest_index = np.argmin(annual_income)
highest_index = np.argmax(annual_income)

print("Customer IDs of lowest and highest annual income is:\n", cust_id[lowest_index], "and", cust_id[highest_index], "respectively.")


Customer IDs of lowest and highest annual income is:
 1.0 and 199.0 respectively.


In [56]:
# Task 4 

indxx = np.where((age<45) & (annual_income>35) & (spend_score>75))

print("---------------------------------------------------------------------------------------------------------------")
print("Details of the customers whose spending score is more than 75, age less than 45, annual income greater than 35K")
print("---------------------------------------------------------------------------------------------------------------")
print("\nCustomer ID:\n",cust_id[indxx])
print("\nAge:\n",age[indxx])
print("\nAnnual Income:\n",annual_income[indxx])
print("\nSpending Score:\n",spend_score[indxx])

---------------------------------------------------------------------------------------------------------------
Details of the customers whose spending score is more than 75, age less than 45, annual income greater than 35K
---------------------------------------------------------------------------------------------------------------

Customer ID:
 [ 42. 124. 126. 128. 136. 142. 144. 146. 150. 152. 154. 156. 158. 162.
 164. 168. 174. 176. 180. 182. 184. 186. 190. 194. 196. 200.]

Age:
 [24. 39. 31. 40. 29. 32. 32. 28. 34. 39. 38. 27. 30. 29. 31. 33. 36. 30.
 35. 32. 29. 30. 36. 38. 35. 30.]

Annual Income:
 [ 38.  69.  70.  71.  73.  75.  76.  77.  78.  78.  78.  78.  78.  79.
  81.  86.  87.  88.  93.  97.  98.  99. 103. 113. 120. 137.]

Spending Score:
 [92. 91. 77. 95. 88. 93. 87. 97. 90. 88. 76. 89. 78. 83. 93. 95. 92. 86.
 90. 86. 88. 97. 85. 91. 79. 83.]


In [85]:
# task 5

# Generating random inputs from $10 to $50 for 200 employees 
gift_coupons = np.random.randint(10,51, 200)
print("Random Gift Coupons from the company:\n\n", gift_coupons)
# Adding new column to main data

new_data = np.column_stack((Data, gift_coupons))
print("\nData after adding new 5th column as 'Gift Coupons' is:\n", new_data)

Random Gift Coupons from the company:

 [33 40 45 28 18 28 25 47 13 36 42 13 14 13 33 19 25 23 23 48 12 38 26 22
 34 27 27 16 21 10 15 43 48 49 24 43 49 20 21 19 47 33 30 35 13 12 43 10
 21 36 13 15 31 44 45 33 23 39 19 14 37 32 46 10 37 43 33 22 22 24 45 49
 14 31 17 20 46 20 20 29 40 17 19 15 46 36 16 18 12 37 17 43 24 50 10 29
 22 26 13 26 38 26 34 27 48 33 21 31 13 12 15 46 34 50 49 47 17 48 44 15
 16 16 40 47 26 45 27 21 33 28 22 27 38 29 42 48 12 48 13 13 12 38 39 19
 49 12 41 25 15 11 46 15 35 42 40 26 30 43 44 11 28 17 44 22 26 37 49 49
 11 26 15 46 26 47 34 28 50 13 32 19 50 46 12 26 48 47 26 50 15 32 24 20
 42 22 17 22 32 32 15 25]

Data after adding new 5th column as 'Gift Coupons' is:
 [[  1.  19.  15.  39.  33.]
 [  2.  21.  15.  81.  40.]
 [  3.  20.  16.   6.  45.]
 [  4.  23.  16.  77.  28.]
 [  5.  31.  17.  40.  18.]
 [  6.  22.  17.  76.  28.]
 [  7.  35.  18.   6.  25.]
 [  8.  23.  18.  94.  47.]
 [  9.  64.  19.   3.  13.]
 [ 10.  30.  19.  72.  36.]
 [ 11.  67.  