## University Admission Decision

In [5]:
import numpy as np

In [11]:
# Task 1

from numpy import genfromtxt

adm_data = genfromtxt('DS1_C4_S1_AdmissionPredict_Data_Practice.csv', delimiter = ',', skip_header = 1)
print(adm_data)

[[  1.   337.   118.   ...   9.65   1.     0.92]
 [  2.   324.   107.   ...   8.87   1.     0.76]
 [  3.   316.   104.   ...   8.     1.     0.72]
 ...
 [398.   330.   116.   ...   9.45   1.     0.91]
 [399.   312.   103.   ...   8.78   0.     0.67]
 [400.   333.   117.   ...   9.66   1.     0.95]]


In [14]:
# Task 2

GRE = adm_data[:,1]
print("GRE Score of all students:\n\n", GRE)

GRE Score of all students:

 [337. 324. 316. 322. 314. 330. 321. 308. 302. 323. 325. 327. 328. 307.
 311. 314. 317. 319. 318. 303. 312. 325. 328. 334. 336. 340. 322. 298.
 295. 310. 300. 327. 338. 340. 331. 320. 299. 300. 304. 307. 308. 316.
 313. 332. 326. 322. 329. 339. 321. 327. 313. 312. 334. 324. 322. 320.
 316. 298. 300. 311. 309. 307. 304. 315. 325. 325. 327. 316. 318. 328.
 332. 336. 321. 314. 314. 329. 327. 301. 296. 294. 312. 340. 320. 322.
 340. 319. 315. 317. 314. 316. 318. 299. 298. 301. 303. 304. 306. 331.
 332. 323. 322. 312. 314. 317. 326. 316. 329. 338. 331. 304. 305. 321.
 301. 320. 311. 310. 299. 290. 296. 327. 335. 334. 310. 308. 301. 300.
 323. 319. 326. 333. 339. 303. 309. 323. 333. 314. 312. 316. 326. 318.
 329. 332. 331. 340. 325. 320. 315. 326. 339. 311. 334. 332. 321. 324.
 326. 312. 315. 309. 306. 297. 315. 298. 318. 317. 329. 322. 302. 313.
 293. 311. 312. 334. 322. 323. 321. 320. 329. 319. 309. 307. 300. 305.
 299. 314. 316. 327. 317. 335. 331. 324. 324. 32

In [23]:
# Task 3

index = np.where(GRE>320)
GRE_morethan_320 = GRE[index]
print("Students with GRE score greater than 320 is:\n\n", GRE_morethan_320)

# Find total number of students with GRE score more than 320

total = GRE_morethan_320.size
print("\n\nThe Total number of Students with GRE score greater than 320 is:", total)

Students with GRE score greater than 320 is:

 [337. 324. 322. 330. 321. 323. 325. 327. 328. 325. 328. 334. 336. 340.
 322. 327. 338. 340. 331. 332. 326. 322. 329. 339. 321. 327. 334. 324.
 322. 325. 325. 327. 328. 332. 336. 321. 329. 327. 340. 322. 340. 331.
 332. 323. 322. 326. 329. 338. 331. 321. 327. 335. 334. 323. 326. 333.
 339. 323. 333. 326. 329. 332. 331. 340. 325. 326. 339. 334. 332. 321.
 324. 326. 329. 322. 334. 322. 323. 321. 329. 327. 335. 331. 324. 324.
 323. 322. 336. 340. 334. 325. 328. 338. 333. 331. 330. 322. 321. 324.
 324. 324. 330. 326. 325. 329. 324. 325. 328. 324. 321. 335. 321. 324.
 326. 331. 327. 324. 325. 327. 322. 329. 321. 340. 331. 336. 324. 330.
 322. 323. 321. 323. 325. 328. 324. 327. 323. 326. 324. 327. 325. 332.
 323. 324. 326. 325. 327. 321. 322. 334. 338. 330. 324. 336. 321. 322.
 324. 340. 335. 326. 329. 324. 325. 330. 333.]


The Total number of Students with GRE score greater than 320 is: 163


In [36]:
# Task 4 

TOEFL = adm_data[:,2]
print("TOEFL Score of all students:\n\n", TOEFL)

indx = np.where(TOEFL>110)
Tofl_morethan_110 = TOEFL[indx]
print("\n\nStudents with TOEFL score greater than 110 is:\n\n", Tofl_morethan_110)

# Calculate chance of admission

chance = adm_data[indx, 8]
print("\n\nChance of Admission is:", chance)
avg = chance.mean()

percent = avg * 100
print("\n\nChance of admission who scores more than 110 in TOEFL is:", percent, "Percentage")

TOEFL Score of all students:

 [118. 107. 104. 110. 103. 115. 109. 101. 102. 108. 106. 111. 112. 109.
 104. 105. 107. 106. 110. 102. 107. 114. 116. 119. 119. 120. 109.  98.
  93.  99.  97. 103. 118. 114. 112. 110. 106. 105. 105. 108. 110. 105.
 107. 117. 113. 110. 114. 119. 110. 111.  98. 100. 116. 112. 110. 103.
 102.  99.  99. 104. 100. 101. 105. 107. 111. 112. 114. 107. 109. 115.
 118. 112. 111. 108. 106. 114. 112.  99.  95.  93. 105. 120. 110. 115.
 115. 103. 106. 107. 108. 109. 106.  97.  98.  97.  99. 100. 100. 120.
 119. 113. 107. 105. 106. 104. 112. 110. 111. 117. 116. 103. 108. 109.
 107. 110. 105. 106. 102. 104.  99. 104. 117. 119. 106. 108. 106. 100.
 113. 112. 112. 118. 114. 105. 105. 112. 113. 109. 103. 100. 116. 109.
 110. 118. 115. 120. 112. 113. 105. 114. 116. 106. 114. 116. 112. 105.
 108. 109. 105. 104. 106. 100. 103.  99. 109. 105. 111. 110. 102. 102.
  97.  99. 101. 117. 110. 113. 111. 111. 119. 110. 108. 102. 104. 107.
 100. 110. 106. 113. 107. 118. 115. 112. 111. 

In [58]:
# Task 5

research = adm_data[:, -2]
print("Research Experience:\n", research)

Indexx = np.where((GRE > 315) & (TOEFL >115) & (research == 1))
print("\n\nIndexes satisfying the condition:\n", Indexx)

#Finding serial number

serial = adm_data[:, 0]
print("\n\nSerial numbers:\n", serial)
serial_of_students = serial[Indexx]
print("\n\nIndexed Serial numbers are:\n", serial_of_students)
print("\n\nThe total number of students eligible for scholarship is:", serial_of_students.size)

Research Experience:
 [1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1.
 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1.
 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0.
 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 1.
 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1.
 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 0. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0.
 0. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1.
 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 1. 1.
 1. 0. 0. 0. 0. 0. 1. 1. 1. 1